version: 2.1
orbs:
  node: circleci/node@4.1

jobs:
  e2e-tests:
    docker:
      - image: cimg/node:15.1-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install npm dependencies
          command: |
            npm install  
            npx playwright install --with-deps
      - run:
          name: Run tests
          command: |
            npm run test
            npm run allureReport
      - store_artifacts:
          path: allure-report/

workflows:
  version: 2
  commit:
    jobs:
      - e2e-tests
  # Commented out this periodical section
  #periodical:
  #  triggers:
  #    - schedule:
   #       cron: "0 10 * * 1-5"
  #        filters:
  #          branches:
  #            only:
  #              - main
  #  jobs:
  #    - e2e-tests
